---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.x-k8s.io.multicluster.x-k8s.io
  resources:
  - inventoryclusters
  - inventoryclusters/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
